services:
  - type: web
    name: spritzai-vt-rag
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: true